### PR TITLE
Move email confirm and password reset to textile pages

### PR DESCRIPTION
**Pull request by michel-cf**
Use textile pages where possible for email confirm and password reset.

For: #624

The text is currently still the same, but can now be changed in the textile page.

### CODE REVIEW

**Comment by PropGit** [comment]
Waiting to merge this once we're past a critical step with Production and Demo.

**Comment by PropGit** [comment]
@zfi - Are we past the critical point where we can merge this in now?

**Comment by zfi** [comment]
Do we need to convert the existing templates to textile files when this PR hits Demo? If that is not an issue, the PR can be committed.

**Comment by zfi** [comment]
I am not seeing where the new textile files are actually replacing the existing mustache files. We may need to build out the new files to replace the content in the old templates.

**Comment by michel-cf** [comment]
@zfi Previously the text on the web pages was hardcoded. Only using the translations file. The whole page content is now replaced by a Textile template.
The never is/was any mustache templates involved with this page. The only page where I use Mustache are the email templates in the Cloud-compiler.

**Pull request merged**
