### PR TITLE
Condensed EEPROM blocks

### PR DESCRIPTION
**Pull request by MatzElectronics**
Creates more condensed and safer EEPROM blocks - more detailed descriptions in the commits.  Also re-hides i2c blocks - it may be some time before those get the attention they need to be used properly.

### CODE REVIEW

**Comment by DarkmatterVale** [comment]
Are we still using the changelog? If so, @MatzElectronics can you please add your changes to the changelog?

Also, friendly reminder, this branch has conflicts that need to be resolved before merging :D

**Comment by MatzElectronics** [comment]
Happy to use the changelog - where it it?  And also, should we add to the changelog when things are verified, or right away?

**Comment by PropGit** [comment]
@DarkmatterVale - I don't really know about this changelog either and doubt that we've been using it regularly.  Is it something that shows up for users of Blockly, or it is just for us developers?

**Comment by michel-cf** [comment]
The change log is accessible for everyone by the links on the bottom of the pages.
http://blockly.parallax.com/blockly/public/changelog

**Comment by PropGit** [comment]
I helped @MatzElectronics with this merge conflict, but from my local repo and fork.  So this PR is now cancelled and #713 replaces it.

**Pull request closed without merging**
