### PR TITLE
Add new Data Types subcategory

### LINKED ISSUE #166: New block category: Data Types
The current data-type blocks are not located together, which can be confusing for beginners. I propose we create a new category under the "Programming" category titled "Data Types" which will contain the following blocks:

- [ ] Integer/Float math block
- [ ] Char/String block (fixes #151)

In addition, blocks related to creating arrays should go into this category.

### PR DESCRIPTION
**Pull request by DarkmatterVale**
Fixes #166 and #151

### CODE REVIEW

**Comment by DarkmatterVale** [comment]
Should I instead place the appropriate blocks within the "Variables" as opposed to creating a whole new subcategory?

**Comment by cbradyatinquire** [comment]
I think we should look around at other projects' solutions for categorizing blocks, to compare & identify mental models likely to be in our users' minds --> 

FOR EXAMPLE:  

>Snap creates a category called "Operators" which contains some things that are in our Math, Conditions, and Variables categories.  In their variables category, you have the "make a variable" pseudoblock.
http://snap.berkeley.edu/run

>Scratch also uses "Operators" but they put their variable creation under a Data category.
https://scratch.mit.edu/projects/editor/?tip_bar=getStarted

**Comment by DarkmatterVale** [comment]
I agree; perhaps we add an additional category "Operators" below the variables category?

**Comment by michel-cf** [comment]
There is still conversation happening on this on. Do you want this merged as is?

**Comment by DarkmatterVale** [comment]
@michel-cf I think it would be best if we wait to merge this. What are your thoughts on this?

**Comment by cbradyatinquire** [comment]
I would agree if we were going to have a quick "decision meeting" and go with a best guess.  IMO, the question won't solve itself, and we have a strong sense that the current organization is broken.  In absence of a meeting, I would urge us to go with a snap/scratch - like solution and get feedback from test users.

Also, I believe we are going to be messing with the categorization quite a bit.  For example, I will add a new issue for the fact that I think that if the Project is a Hackable Electronic Badge, many of the code sections should go away, since they will not work with the HEB and will also be confusing.

**Comment by DarkmatterVale** [comment]
@cbradyatinquire So go ahead and merge for now? Revise if necessary later?

**Comment by cbradyatinquire** [comment]
@DarkmatterVale :   That's what I would suggest.

**Pull request merged**
