### PR TITLE
Project sharing

### PR DESCRIPTION
**Pull request by michel-cf**

### CODE REVIEW

**Comment by PropGit** [comment]
@zfi - I think this is the PR that requires some corresponding database changes.

@zfi and @michel-cf - we should meet before merging this PR.

**Comment by PropGit** [comment]
@zfi and @michel-cf - Amended, no need to meet before merging this PR; the emailed solution this PR is for is following a good technique.  Once the suggested enhancements are in place in the repository, this PR can be amended or replaced and then merged.  Thanks!

**Comment by zfi** [comment]
Database updates have be applied to the Demo server. #0000-0004

**Comment by PropGit** [comment]
Thanks @zfi and @michel-cf.

**Pull request merged**
