### PR TITLE
Fix issues with color blocks - WIP

### PR DESCRIPTION
**Pull request by DarkmatterVale**
There were a number of issues and this PR should fix all of them.

Do not merge yet because the functions that these blocks rely on are not in SimpleLibraries yet and the code might need to change...

### CODE REVIEW

**Comment by MatzElectronics** [comment]
Please hold on this pull - specifically the "Switch color backend..." as I need to get those functions into Simple Libraries.  Thanks!

**Comment by PropGit** [comment]
@DarkmatterVale @MatzElectronics - Okay, it's on hold until further notice.

**Comment by zfi** [comment]
@DarkmatterVale do you want to resubmit with changes that do not require the updates to the Simple Libraries?

**Comment by DarkmatterVale** [comment]
@zfi It'd be better to just wait for the libraries because many of the calculations cause errors otherwise (I'm having trouble getting it to work right)

**Comment by DarkmatterVale** [comment]
Also fixes #341

**Comment by DarkmatterVale** [comment]
This should be ready to go now...

**Comment by zfi** [comment]
The latest Simple Library update has been deployed to Demo.

**Pull request merged**
