### PR TITLE
Major block updates

### PR DESCRIPTION
**Pull request by DarkmatterVale**
Fixes:

- #300 
- #340 
- #338 
- #344 
- #341 
- #334 
- #333 
- #314 
- #313 
- #382 
- #312 
- #376 
- #372 
- #396 
- #363 
- #337 
- #276

### CODE REVIEW

**Comment by DarkmatterVale** [comment]
Still to be verified:

- #341 
- #376 (needs an update)
- #396 (needs an update)

**Comment by DarkmatterVale** [comment]
Both of the issues that need updates have been updated.

**Comment by PropGit** [comment]
Not sure about #376.  @zfi committed an update for that recently that still needs verification.  Will this PR need to be updated when it's verified?  Probably better to merge this and then merge a new PR with the updates @zfi submitted right after, once #376 is verified.

Also, Issue #317 still needs fix/verification.

**Comment by CarsonGracey** [comment]
@PropGit, issues #376 and #317 are now verified.

**Comment by PropGit** [comment]
Finalized.  Approved for merging into master now.

**Pull request merged**
