### PR TITLE
Demo

### PR DESCRIPTION
**Pull request by RobotBASIC**
Use of the READ A/D pins for the S3 (Beta mode) gives compile errors.
Trying to copy blocks from the Demo mode does not solve the problem.
This is the error...

Required libraries: s3, fdserial, simpletools
Library compile order: None needed
single.c: In function 'main':
single.c:21:23: error: 'S3_ADC_Anull' undeclared (first use in this function)
single.c:21:23: note: each undeclared identifier is reported only once for each function it appears in

### CODE REVIEW

**Comment by MatzElectronics** [comment]
Correct - I believe it's finally working in demo, but we finalizing testing
and planning an update to beta (production) on or before Jan. 5th.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
@RobotBASIC - Are you interested in contributing?  We'd love to have help!  I'm going to close this one PR because there is a bit of a process and a few merge conflicts that have to be resolved first, plus we will actually be pushing the 0.99 branch into the production (BETA) site when we do the update on of before Jan. 5th.  If you'd like an orientation, just let me know!

**Comment by RobotBASIC** [comment]
Happy to help.
Also I have found a couple of minor things.
1) My S3 has trouble with black electrical tape as a line even when I run the calibration.  My first guess is that the calibration needs a little tweaking.  One nice option would be command to actually set the line sensor threshold.
2) Under motors, the rotate command cannot use variables for degrees or speed (even though other motor commands use variables).  It would be nice if this could use variables too - and much more consistent.

**Comment by MatzElectronics** [comment]
I agree with both ideas - go ahead and open issues for both, and let's work
through them.
Thanks!

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Pull request closed without merging**
