### PR TITLE
More bug fixes

### LINKED ISSUE #264: Set LED State block produces no C code (suppresses any C-code if used)
if this block is used in a program, the C-code view shows up empty.

screen shot 2016-06-24 at 2 10 18 pm

### LINKED ISSUE #274: Correction to the Sony Remote block code
When I created These blocks:
screen shot 2016-06-27 at 10 47 17 am

I got this C code:
```

#include "simpletools.h"
#include "sirc.h"

int remote;

int main() {
  sirc_setTimeout( 70 );

  remote =  s;

}

```

And when I went into Simple IDE I was able to change it to this:

```
#include "simpletools.h"
#include "sirc.h"

int remote;

int main() {
  sirc_setTimeout( 70 );

  remote = sirc_button(10);

}
```

Where I changed the "remote = s;" into "remote = sirc_button(10)"  And it was able to work. -Blake

### LINKED ISSUE #276: Wave play back block generates wrong code
snip4
These are the blocks used 

This is the code generated by Blockly
```
#include "simpletools.h"
#include "wavplayer.h"


int main() {

  const char filetechloop[] = {"techloop"};
  wav_play(techloop);
  wav_volume(10);
  pause(50000);
  wav_stop();

}
```

This is the corrected code 
```
#include "simpletools.h"
#include "wavplayer.h"
int main() {
  int DO = 22, CLK = 23, DI = 24, CS = 25;        // SD I/O pins
  sd_mount(DO, CLK, DI, CS);                      // Mount SD card

    const char filetechloop[] = {"techloop.wav"};
    wav_play("techloop.wav");
    
    wav_volume(10);
    pause(50000);
  }
```

-Roxy

### LINKED ISSUE #277: Update for servo_setramp
In issue #265 I said that `servo_speed` needs to be changed to `drive_speed` while adding `#include "abdrive.h" ` This was incorrect because `#include "abdrive.h" ` requires encoders since it is used with the ActivityBot. This library needs to be changed to `#include servo.h"`, while also reverting `drive_speed` back to `servo_speed` that means that the changes @DarkmatterVale made in the last PR commit #272 specifically here: https://github.com/parallaxinc/BlocklyProp/pull/272/commits/999ca3c800e0fd336522b015d3d91c542d576349

### LINKED ISSUE #278: Modification of Servo Set Ramp
The Servo Set Ramp block needs to have a range of 0-100 with a default of 50. Values entered above 100, would default to 100 while all negative values would default to 0. The library that would need to be included would be `"servo.h"`. This would be helpful if added because the maximum range of step values for Servo Set Ramp is currently 1-20.

### LINKED ISSUE #279: boolean substitution still around for random() block
the RANDOM block works when the value is directly printed 
but when it's stored to a variable, that variable is initialized with "boolean" type

### LINKED ISSUE #280: print-a-number block should not print the variable name and "="
because we can print these prefix things directly using print-a-string it would be better for this block just to print a number alone.

### PR DESCRIPTION
**Pull request by DarkmatterVale**
Most of the general C bugs should be fixed after this PR. @kgracey most of the points we talked about will be sent in different PRs.

- Fixes #280 
- Fixes #279 
- Fixes #278  
- Fixes #277 
- Fixes #276 
- Fixes #274 
- Fixes #264

### CODE REVIEW

**Comment by DarkmatterVale** [comment]
- Fixes #283

**Comment by michel-cf** [comment]
Vale, don't forget to also redo the spin toolbox. Otherwise we'll be stuck with missing translations there.
Just reorder them like you are doing (have done) for C.

**Comment by DarkmatterVale** [comment]
Good point...

**Comment by DarkmatterVale** [comment]
@kgracey, would you like this one to be merged into master & be published immediately (because of the numerous bug fixes) or should I send a new PR for the demo branch?

**Comment by michel-cf** [comment]
Keep in mind that if you ever merge something into the demo branch that you also edit the change-log.

**Comment by DarkmatterVale** [comment]
Gotcha; if Mr. Gracey wants this merged into demo then I will update the changelog

**Pull request closed without merging**
