### PR TITLE
Many fixes

### PR DESCRIPTION
**Pull request by DarkmatterVale**
These have been tested pretty well, and fix many issues (as @CarsonGracey has confirmed in numerous issues). Further, I am starting to run into issues when creating new branches to fix many issues because I am building on commits in this branch.

### CODE REVIEW

**Comment by DarkmatterVale** [comment]
bump

**Comment by kgracey** [comment]
Upvote. Push this stuff to the moon @DarkmatterVale. Thank you for bringing the need to ratify this important set of amendments (which we requested) into the official distribution! Press that button!

**Comment by PropGit** [comment]
Wait.... Issue #282 does not appear to be verified fixed.

**Comment by PropGit** [comment]
Issue #282 is now verified as fixed.

I approve of @DarkmatterVale merging this to master.

**Pull request merged**
