### PR TITLE
Implement the Variables declare block

### PR DESCRIPTION
**Pull request by DarkmatterVale**
This should give the user the ability to select the type for a variable. @kgracey this is the first of the changes that we discussed.

### CODE REVIEW

**Comment by michel-cf** [comment]
This merge request will not change anything because this file is not used directly.

**Comment by DarkmatterVale** [comment]
Well that's unfortunate...Do you know where I need to look to make those changes? blocky_uncompressed.js?

**Comment by DarkmatterVale** [comment]
bump

**Comment by michel-cf** [comment]
If it was only so easy. It's in blockly_compressed.js.

To do this, we need to branch Blockly. And then do our modifications on it. Then we can compress it and copy that to BlocklyProp.
That will be easier then using Blockly as a submodule.

I'll need to see with Jeff about creating a Blockly branch under Parallax control where we can work on. But that we also can update with the Blockly master branch.

**Comment by DarkmatterVale** [comment]
Ah, ok; so take a break on this one for a little bit?

**Comment by michel-cf** [comment]
Yes. Once we have this new project set up. We can make more changes to the core of blockly.

If I made changes I always had to find the location in the single compressed javascript file.

**Comment by DarkmatterVale** [comment]
Ok; I will close this for now then...

**Pull request closed without merging**
