### PR TITLE
Help documents

### PR DESCRIPTION
**Pull request by DarkmatterVale**
This is a work in progress. I have created this PR to make it easy for the Parallax reviewers to look at my work.

### CODE REVIEW

**Comment by DarkmatterVale** [comment]
This PR should be closed since documentation will go into a separate repo. @michel-cf has the other repo been created?

**Comment by michel-cf** [comment]
The new repo hasn't yet been created, although the help system has been created in the BlocklyProp server. Including textile to html conversion and indexing for full text search.

I will prioritize creation and basic setup of the help repository.

**Comment by DarkmatterVale** [comment]
Awesome, thank you @michel-cf !!

**Comment by DarkmatterVale** [comment]
I'm closing this because I am working on migrating the documentation to the other repository.

**Pull request closed without merging**
