### PR TITLE
 Restore projectlink capability, delete unused files, condense js files

### PR DESCRIPTION
**Pull request by MatzElectronics**
Addresses #1367 

Removes files that were previously (and safely) removed in the "Wild west" version of demo.  Removes separate copy of the blockly editor (blockly-c-editor.jsp), and instead pushes the project retrieved via the shared link via a b64-encoded meta tag.

### CODE REVIEW

**Comment by zfi** [comment]
Commit 93dc989 ensures that all new projects are of type PROPC. We should take one more pass in the database to ensure that there are no remaining SPINC type projects. We should also update code on the server side to reflect this reality. I'm OK with the PR as long as we put a pin in the server side updates before 0.100 goes out.

**Comment by MatzElectronics** [comment]
Any project that has a modified date on or before Oct 4, 2017 will need to be examined carefully.  Any project modified before that date is okay.

**Comment by MatzElectronics** [comment]
Simply running them through the transmogrifier (ProjectDaoImpl) will clean them up properly - then that code (and any SPIN reference/code) can be safely removed.

**Comment by zfi** [comment]
>> Any project that has a modified date on or before Oct 4, 2017 will need to be examined
>> carefully. Any project modified before that date is okay.

Um, which is it? Projects modified before 10/4/2017 should be examined carefully, or any project modified before 10/4/2017 is OK?

**Comment by MatzElectronics** [comment]
Sorry modified after is okay.  Older projects need to be assessed

**Pull request merged**
