### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by MatzElectronics**
Found a bug, squishing it.

### CODE REVIEW

**Comment by zfi** [comment]
PRs need some description of what the code change is attempting to do. My only concern with the patch is that the original code worked against an array where as the patch does not.

**Comment by MatzElectronics** [comment]
Sorry!  That's actually what was making it choke.  It was unnecessary and
incorrect.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by zfi** [comment]
In demo at 2:15 PM PT

**Comment by MatzElectronics** [comment]
Confirmed working, thanks!

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Pull request merged**
