### PR TITLE
Add Sound Impact blocks

### PR DESCRIPTION
**Pull request by DarkmatterVale**

### CODE REVIEW

**Comment by michel-cf** [comment]
I really don't like the fallback if you don't have initialized the cog.
- sound_impact_get will generate invalid code as it doesn't return anything, at least return a number
- sound_impact_end code is just not present. I would at least show a comment in the generated code that the init is missing

**Comment by DarkmatterVale** [comment]
@PropGit Is it alright if I return -1? Is there a specific error code you would like to see returned?

**Comment by DarkmatterVale** [comment]
@michel-cf What would you recommend as a tooltip? Maybe "Ensure the sound impact sensor has been initialized before using this block"?

**Comment by michel-cf** [comment]
Sounds good to me

**Comment by DarkmatterVale** [comment]
Does it look better now?

**Pull request merged**
