### PR TITLE
Base64 encode propc files before saving

### PR DESCRIPTION
**Pull request by MatzElectronics**

### CODE REVIEW

**Comment by PropGit** [comment]
@MatzElectronics - Can you tell me why this is necessary and does it affect (or imply that we'll need to do the same for) the Cloud Compiler interaction with the local web client?

**Comment by MatzElectronics** [comment]
This is specifically for projects that are propc-only code.  In order to
store the propeller c that's user has edited into a do that expects blocks
(XML), the users code has to be wrapped with a "block".  Some of the
characters that can be used in C cause the XML to look poorly formatted to
the browser when it tries to read it.  Not fatal, but still an error, and
one possible cause for why it was having trouble with saving the files
occasionally (it might still be...working on this)

This process also required a blockId to be generated.  Since it was random,
it was regenerated each time a user saved or loaded, which also meant that
if the user didn't change their code, it still looked different in a text
compare, so it was throwing save-check warnings when it didn't need to.
The new code generates a blockId by using the last 20 chars of the base64
encoded users propc minus any padding that's part of the base64 standard.

This does not affect normal block projects in any way.

**Comment by zfi** [comment]
Placing the 'C' code within a CDATA XML tag should resolve the issue of the extraneous characters fouling up the XML pattern.

**Comment by MatzElectronics** [comment]
I thought about that too...but then the blockly generator can't retrieve
it.  It has to be in a <field> tag

**Pull request merged**
