### PR TITLE
Fix 301

### PR DESCRIPTION
**Pull request by DarkmatterVale**

### CODE REVIEW

**Comment by DarkmatterVale** [comment]
As you can see, a few other PRs need to be merged first...

**Comment by DarkmatterVale** [comment]
This also fixes #359

**Comment by PropGit** [comment]
Just as a matter of formality (it was said before in another PR): Issues #290 and #317 are not yet verified fixed.

**Comment by DarkmatterVale** [comment]
I just cleaned up the commits on this branch to make it much more organized; I also removed the references to other issues. Can I go ahead and merge @PropGit ?

**Comment by PropGit** [comment]
@DarkmatterVale - Yes, this can be merged.

**Pull request merged**
